version: "3"

services:
  mongodb-user:
    image: mongo:latest
    container_name: mongodb-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./userDb/db:/userDb/db

  mongodb-transaction:
    image: mongo:latest
    container_name: mongodb-transaction
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./transactionDb/db:/transactionDb/db

  mongodb-group:
    image: mongo:latest
    container_name: mongodb-group
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./groupDb/db:/groupDb/db

  # user_service_server:
  #   container_name: user_service_server
  #   env_file: "./user-service/.env"
  #   build:
  #     context: ./user-service
  #     dockerfile: ./Dockerfile
  #   image: "user-service"
  #   environment:
  #     USER_ENV: user_service_docker
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mongodb-user

  # transaction_service_server:
  #   container_name: transaction_service_server
  #   env_file: "./transaction-service/.env"
  #   build:
  #     context: ./transaction-service
  #     dockerfile: ./Dockerfile
  #   image: "transaction-service"
  #   environment:
  #     TRANSACTIONS_ENV: transaction_service_docker
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - mongodb-transaction

  # notification_service_server:
  #   container_name: notification_service_server
  #   env_file: "./notification-service/.env"
  #   build:
  #     context: ./notification-service
  #     dockerfile: ./Dockerfile
  #   image: "notification-service"
  #   environment:
  #     TRANSACTIONS_ENV: notification_service_docker
  #   ports:
  #     - "5003:5003"
